SELECT Player_id, COUNT(*)
FROM goat.totals_stats
WHERE ast>= (tov*2) 
GROUP BY Player_id;


/*
PULLS PLAYER NAME AND THE COUNT
OF TIMES WHERE THEIR ASSIST TOTALS 
ARE MORE THAN 2X THEIR TURNOVER TOTALS
FOR THE SAME SEASON
*\
