SELECT player_id, round(AVG(`TS%`)*100,2) AS AVG_TS_PERCENT
FROM advanced_stats
GROUP BY player_id;


/*
PULLS PLAYER NAME AND TRANSFORMS THE TRUE SHOOTING PERCENTAGE FROM A DECIMAL TO A PERCENTAGE
AND RENAMES THE COLUMN AS AVG_TS_PERCENT. THUS, CLEANING THE DATA.
*\
